{{- if .Values.experimentalGateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .Values.experimentalGateway.name }}
  rules:
  - backendRefs:
    - group: inference.networking.k8s.io
      kind: InferencePool
      name: {{ .Release.Name }}
    matches:
    - path:
        type: PathPrefix
        value: /
      {{- if .Values.experimentalGateway.baseModel }}
      headers:
        - type: Exact
          name: X-Gateway-Base-Model-Name
          value: {{ .Values.experimentalGateway.baseModel }}
      {{- end }}
    timeouts:
      request: 300s
{{- end }}
