{{ include "inference-extension.config" . }}
{{ include "inference-extension.deployment" . }}
{{ include "inference-extension.lead-election-rbac" . }}
{{ include "inference-extension.sa-token-secret" . }}
{{ include "inference-extension.service" . }}
{{ include "inference-extension.service-monitor" . }}
