apiVersion: v2
name: inferencepool
description: A Helm chart for InferencePool

type: application

version: 0.0.0

appVersion: "0.0.0"
dependencies:
  - name: inference-extension
    version: 0.0.0
    repository: "file://../inference-extension"
    # This is needed to make use of the common values.yaml in ./config/charts/inference-extension/values.yaml
    alias: inferenceExtension
