{{- if .Values.bbr.multiNamespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bbr-configmap-reader
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bbr-configmap-reader
subjects:
- kind: ServiceAccount
  name: {{ .Values.bbr.name }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bbr-configmap-reader
{{- else }} ## if bbr is set in a single namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.bbr.name }}-{{ .Release.Name }}-configmap-reader
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.bbr.name }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.bbr.name }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.bbr.name }}-{{ .Release.Name }}-configmap-reader
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ Values.bbr.name}}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
