apiVersion: v1
kind: ConfigMap
metadata:
  name: vllm-llama3-8b-instruct-adapters-allowlist
  labels:
    inference-gateway.k8s.io/managed: "true"
data:
  baseModel: meta-llama/Llama-3.1-8B-Instruct
  adapters: |
    - food-review-1
