apiVersion: v2
name: epp-standalone
description: A Helm chart for Endpoint Picker

type: application

version: 0.0.0

appVersion: "0.0.0"

dependencies:
  - name: inference-extension
    version: 0.0.0
    repository: "file://../inference-extension"
